name: Dynmap-Multiverse
version: "${project.version}"
main: org.dynmap.multiverse.DynmapMultiversePlugin
description: A bridge to display Multiverse Anchors in Dynmap
depend: [dynmap, Multiverse-Core]